// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {glob} from '../models';

export function AddEvent(arg1:string):Promise<void>;

export function CheckRules():Promise<void>;

export function DeleteBackup(arg1:string,arg2:string):Promise<void>;

export function DownloadRules():Promise<void>;

export function GetActiveBackups():Promise<{[key: string]: Array<main.BackupMetadata>}>;

export function GetActiveMonitors():Promise<Array<main.Monitor>>;

export function GetActiveRules():Promise<{[key: string]: main.ActiveRule}>;

export function GetConfig():Promise<main.Config>;

export function GetErrors():Promise<Array<string>>;

export function GetEvents():Promise<Array<string>>;

export function GetPathSeparator():Promise<string>;

export function GetRules():Promise<{[key: string]: main.ActiveRule}>;

export function IsRunning(arg1:glob.Glob):Promise<boolean>;

export function LoadConfig():Promise<void>;

export function LoadRules():Promise<void>;

export function ReportError(arg1:Error):Promise<void>;

export function RestoreBackup(arg1:string,arg2:string):Promise<boolean>;

export function SaveConfig():Promise<void>;
