// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEvent(arg1) {
  return window['go']['main']['App']['AddEvent'](arg1);
}

export function CheckRules() {
  return window['go']['main']['App']['CheckRules']();
}

export function DeleteBackup(arg1, arg2) {
  return window['go']['main']['App']['DeleteBackup'](arg1, arg2);
}

export function DownloadRules() {
  return window['go']['main']['App']['DownloadRules']();
}

export function GetActiveBackups() {
  return window['go']['main']['App']['GetActiveBackups']();
}

export function GetActiveMonitors() {
  return window['go']['main']['App']['GetActiveMonitors']();
}

export function GetActiveRules() {
  return window['go']['main']['App']['GetActiveRules']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetErrors() {
  return window['go']['main']['App']['GetErrors']();
}

export function GetEvents() {
  return window['go']['main']['App']['GetEvents']();
}

export function GetPathSeparator() {
  return window['go']['main']['App']['GetPathSeparator']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function IsRunning(arg1) {
  return window['go']['main']['App']['IsRunning'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadRules() {
  return window['go']['main']['App']['LoadRules']();
}

export function ReportError(arg1) {
  return window['go']['main']['App']['ReportError'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}
