name: Build

on:
  push:
    branches:
      - "main"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.0"

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor

      - name: Prepare things
        run: |
          mkdir artifacts
          cd frontend
          pnpm install

      - name: Build for Linux amd64
        run: |
          wails build --platform linux/amd64
          cp -a build/bin/baacup artifacts/baacup-linux-amd64

      # TODO: Crashes with some assembler no such instruction bla bla - maybe needs ARM runner?
      #      - name: Build for Linux arm64
      #        run: |
      #          wails build --platform linux/arm64
      #          cp -a build/bin/baacup artifacts/baacup-linux-arm64

      - name: Build for Windows amd64
        run: |
          wails build --platform windows/amd64
          cp -a build/bin/baacup.exe artifacts/baacup-windows-amd64.exe

      - name: Build for Windows arm64
        run: |
          wails build --platform windows/amd64
          cp -a build/bin/baacup.exe artifacts/baacup-windows-arm64.exe

      # TODO: macOS build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            artifacts
