name: Validate Pull Request

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.0"

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install tools
        run: |
          mkdir -p frontend/dist
          touch frontend/dist/blah.txt

          pip install pre-commit
          go install github.com/lietu/go-pre-commit@latest
          go install github.com/kisielk/errcheck@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest

          cd frontend
          pnpm install
          pnpm add -g eslint

      - name: Run pre-commit
        run: pre-commit run --all-files || exit 1
